### ISSUE TITLE
CORS from Overwolf app

### ISSUE THREAD

**Issue by OskarD** [TeKrop/overfast-api#198] opened 2024-10-08 11:26 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to use the API from an Overwolf app I'm building, but it's blocked by CORS policy:
```
Access to fetch at 'https://overfast-api.tekrop.fr/players/Ashe62-2685/summary' from origin 'overwolf-extension://jibicdemenmbbgklpbgioihcacpgefpphlffhanp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Would it be possible to allow the `overwolf-extension://` protocol?

**Comment by OskarD** [comment] 2024-10-08 13:43
It actually looks like successful requests go through, but when I search for a private or invalid profile (Like the one above) it gives me 404 with no-CORS

**Comment by TeKrop** [comment] 2024-10-08 19:33
Hello ! Good catch, thank you for the report !
The header wasn't added for 4xx/5xx errors, I fixed the issue 👍 
Let me know if it works as expected

**Comment by OskarD** [comment] 2024-10-08 23:09
Seems like it's working, thanks a lot! 🥳

**Comment by OskarD** [comment] 2024-10-17 20:56
This started happening again 😅

**Comment by TeKrop** [comment] 2024-10-17 21:37
Woops, I made an update on nginx settings handling (better decoupling), and it seems to have affected this particular case 😅
I made an update a few minutes ago, and it seems to be better now.

I can see a lot of logs coming from OverwolfClient user agent, I assume this is your extension ? I can see some duplicate calls, is it an expected behaviour ? Or maybe you're doing some testing ? 🤔 

Also, it seems to make too many calls, Blizzard is temporarily banning the API from time to time 😅 (HTTP 403 from Blizzard).

I'll see what I can do to prevent this from happening, I may have to adjust the way I configured the rate limit 🤔

**Comment by OskarD** [comment] 2024-10-17 22:01
Haha whoops! Yes, that's my app (Not extension :))

It sounds like expected behavior, every match my users load into fetches the profiles of all its players. It can be up to 12 I think (In custom game modes) and it retries after 1 second if it gets return code 429. I figured that should be fine since the documentation says 30 requests/IP/second, but I seem to be getting 429 after only like 8 for some reason.

If you need me to change the behavior, please let me know 🙏

**Comment by OskarD** [comment] 2024-10-17 22:03
Also:
```
Access to XMLHttpRequest at 'https://overfast-api.tekrop.fr/players/Comfy-21956' from origin 'overwolf-extension://jibicdemenmbbgklpbgioihcacpgefpphlffhanp' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
```

**Comment by TeKrop** [comment] 2024-10-17 22:20
Ah, yes, that makes sense 👍

The 30 requests per IP per second limit was initially set somewhat arbitrarily to manage the server load, but I didn’t anticipate hitting a 403 error from Blizzard. This week is actually the first time I've encountered that since the beginning of the project 😅 I'll likely adjust the rate limit to better address this issue tomorrow 🤔 

In the meantime, could you set a higher retry delay on your end ? Maybe something like 3-4s 🤔 

Also fixed the last CORS issue you mentioned 👍

**Comment by OskarD** [comment] 2024-10-17 22:24
Yeah, I can definitely do that. Or maybe I should batch the requests instead? Do you know what size is the largest I can send per second (or however seconds you prefer) without causing any issues with the current load?

**Comment by OskarD** [comment] 2024-10-17 22:26
Maybe we should discuss this outside of this ticket, would you like to join my Discord server? If I'm lucky, the amount of users will increase over the next few week and it might be good for you to be able to reach me as well. Here is a temporary invite: https://discord.gg/3vYheJEG

**Comment by TeKrop** [comment] 2024-10-19 12:52
> Yeah, I can definitely do that. Or maybe I should batch the requests instead? Do you know what batch size (Concurrent requests) is the largest I can send per second (or however seconds you prefer) without causing any issues with the current load?

I don't know the batch size for which it's causing issues for now, I'll make some analysis and keep you updated 👍 
Anyway, maybe you can limit to 2-3 concurrent requests ? And less than 5r/s in total in the meantime ?
FYI, to prevent issues happening to everyone using the APIs, I'm thinking about putting a limitation at API level as well 🤔

Regarding your Discord link, it doesn't work anymore, but indeed it would be nice to discuss it outside of this issue 👍 Do you have the same username on Discord ? I sent you an invite if that's the case

**Comment by OskarD** [comment] 2024-10-19 13:35
> I don't know the batch size for which it's causing issues for now, I'll make some analysis and keep you updated 👍 Anyway, maybe you can limit to 2-3 concurrent requests ? And less than 5r/s in total in the meantime ? FYI, to prevent issues happening to everyone using the APIs, I'm thinking about putting a limitation at API level as well 🤔

Thanks, that would be great! Let's discuss this on Discord, I think that's best

> Regarding your Discord link, it doesn't work anymore, but indeed it would be nice to discuss it outside of this issue 👍 Do you have the same username on Discord ? I sent you an invite if that's the case

I think it expired, try this one: https://discord.gg/XDYshnKw

**Comment by TeKrop** [comment] 2024-10-19 14:37
Main issue solved, I'm closing this issue 👍

**Closed by TeKrop** 2024-10-19 14:37 UTC
Labels: enhancement
